Adding port option for Theia template
okteto/charts pull request #87
Opened 2020-09-12 01:08 UTC by firatoezcan

Hey, I tested out the Theia chart from the pre-built templates and my application wants to access port 3000 and that didn't quite work out. Checked quickly and there's a theia cli flag to specify the port so this PR adds that to it.

I also added it to the values-okteto.yaml to make it clear for users why their application may not be running

2020-09-12 01:12 UTC, rberrelleza commented on theia/values-okteto.yaml
> +# This is the port that Theia is running on. Change this if you want to use this port instead
Can you put it after `repository`?

2020-09-12 01:13 UTC, rberrelleza requested changes
Looks good! 

Could you change the order of the keys in values-okteto.yml? We want to put the more common first.

2020-09-14 11:10 UTC, firatoezcan commented on theia/values-okteto.yaml
> +# This is the port that Theia is running on. Change this if you want to use this port instead
Sure :)

2020-09-14 11:15 UTC, pchico83 approved these changes

2020-09-14 14:57 UTC, rberrelleza approved these changes

2020-09-14 14:58 UTC, rberrelleza commented
Thanks for your contribution @firatoezcan!

2020-09-14 14:58 UTC, merged